In [1]:
import numpy as np
import pandas as pd

In [2]:
import zipfile
import os

# Specify the path to the zip file and the extraction directory
zip_file_path = 'D:\Projects\Algo_daily\iris.zip'
extraction_dir = 'D:\Projects\Algo_daily'

# Open the zip file in read mode ('r') and extract all contents
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extraction_dir)

print(f"All files extracted to '{extraction_dir}'")

All files extracted to 'D:\Projects\Algo_daily'


<>:5: SyntaxWarning: invalid escape sequence '\P'
<>:6: SyntaxWarning: invalid escape sequence '\P'
<>:5: SyntaxWarning: invalid escape sequence '\P'
<>:6: SyntaxWarning: invalid escape sequence '\P'
C:\Users\doston\AppData\Local\Temp\ipykernel_2664\3872162872.py:5: SyntaxWarning: invalid escape sequence '\P'
  zip_file_path = 'D:\Projects\Algo_daily\iris.zip'
C:\Users\doston\AppData\Local\Temp\ipykernel_2664\3872162872.py:6: SyntaxWarning: invalid escape sequence '\P'
  extraction_dir = 'D:\Projects\Algo_daily'


In [6]:
import numpy as np
x=np.loadtxt('D:\Projects\Algo_daily\iris.data',usecols=(0,1,2,3),delimiter=',')
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

<>:2: SyntaxWarning: invalid escape sequence '\P'
<>:2: SyntaxWarning: invalid escape sequence '\P'
C:\Users\doston\AppData\Local\Temp\ipykernel_2664\1441952901.py:2: SyntaxWarning: invalid escape sequence '\P'
  x=np.loadtxt('D:\Projects\Algo_daily\iris.data',usecols=(0,1,2,3),delimiter=',')


In [7]:
x.shape

(150, 4)

In [9]:
import numpy as np
x=np.loadtxt('D:\Projects\Algo_daily\iris.data',usecols=(0,1,2,3),delimiter=',')
# print(x)

def kv(x,y):
    b = 0
    for i in range(len(x)):
        b += (x[i]-y[i])**2
    return b**(1/2)

b = np.zeros(shape=(150,150))
for i in range(len(x)):    
    for j in range(i,len(x)):   
        b[i][j] = kv(x[i],x[j])

# print(b)

maksimal = 0
i1 = 0
j1 = 0
for i in range(len(b)):
    for j in range(i,len(b)):
        if b[i][j] > maksimal:
            maksimal = b[i][j]
            i1 = i
            j1 = j

print(f"eng uzoq masofa: {maksimal} qator: {i1} ustun: {j1}")

minimal = maksimal
i2 = 0
j2 = 0
for i in range(len(b)):
    for j in range(i,len(b)):
        if b[i][j] < minimal and b[i][j] != 0:
            minimal = b[i][j]
            i2 = i
            j2 = j

print(f"eng yaqin masofa: {minimal} qator: {i2} ustun: {j2}")

eng uzoq masofa: 7.085195833567341 qator: 13 ustun: 118
eng yaqin masofa: 0.09999999999999964 qator: 7 ustun: 39


<>:2: SyntaxWarning: invalid escape sequence '\P'
<>:2: SyntaxWarning: invalid escape sequence '\P'
C:\Users\doston\AppData\Local\Temp\ipykernel_2664\1298853813.py:2: SyntaxWarning: invalid escape sequence '\P'
  x=np.loadtxt('D:\Projects\Algo_daily\iris.data',usecols=(0,1,2,3),delimiter=',')
